// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CollectStatus():Promise<model.CollectStatus>;

export function GetAutoSyncInterval():Promise<number>;

export function GetDashboardData():Promise<model.DashboardData>;

export function GetTimeSeriesData():Promise<model.TimeSeriesData>;

export function ImportCSV():Promise<model.CSVImportResult>;

export function SetAutoSyncInterval(arg1:number):Promise<void>;

export function StartCollection():Promise<boolean>;

export function StartFullCollection():Promise<boolean>;
