// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function CollectStatus() {
  return window['go']['main']['App']['CollectStatus']();
}

export function DetectCCSwitchDB() {
  return window['go']['main']['App']['DetectCCSwitchDB']();
}

export function GetAutoSyncInterval() {
  return window['go']['main']['App']['GetAutoSyncInterval']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTimeSeriesData() {
  return window['go']['main']['App']['GetTimeSeriesData']();
}

export function ImportCCSwitchDB() {
  return window['go']['main']['App']['ImportCCSwitchDB']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetAutoSyncInterval(arg1) {
  return window['go']['main']['App']['SetAutoSyncInterval'](arg1);
}

export function StartCollection() {
  return window['go']['main']['App']['StartCollection']();
}

export function StartFullCollection() {
  return window['go']['main']['App']['StartFullCollection']();
}

export function UpdatePricing() {
  return window['go']['main']['App']['UpdatePricing']();
}
