// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function CollectStatus() {
  return window['go']['main']['App']['CollectStatus']();
}

export function CreateQuotaConfig(arg1) {
  return window['go']['main']['App']['CreateQuotaConfig'](arg1);
}

export function CurrentOp() {
  return window['go']['main']['App']['CurrentOp']();
}

export function DeleteQuotaConfig(arg1) {
  return window['go']['main']['App']['DeleteQuotaConfig'](arg1);
}

export function DetectCCSwitchDB() {
  return window['go']['main']['App']['DetectCCSwitchDB']();
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function FetchAllQuota() {
  return window['go']['main']['App']['FetchAllQuota']();
}

export function FetchQuota(arg1) {
  return window['go']['main']['App']['FetchQuota'](arg1);
}

export function GetAutoSyncInterval() {
  return window['go']['main']['App']['GetAutoSyncInterval']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetProviderSchemas() {
  return window['go']['main']['App']['GetProviderSchemas']();
}

export function GetSessionModelBreakdown(arg1) {
  return window['go']['main']['App']['GetSessionModelBreakdown'](arg1);
}

export function GetSessionsData() {
  return window['go']['main']['App']['GetSessionsData']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTimeSeriesData(arg1) {
  return window['go']['main']['App']['GetTimeSeriesData'](arg1);
}

export function ImportData() {
  return window['go']['main']['App']['ImportData']();
}

export function ListQuotaConfigs() {
  return window['go']['main']['App']['ListQuotaConfigs']();
}

export function RenameDevice(arg1, arg2) {
  return window['go']['main']['App']['RenameDevice'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetAutoSyncInterval(arg1) {
  return window['go']['main']['App']['SetAutoSyncInterval'](arg1);
}

export function StartCollection() {
  return window['go']['main']['App']['StartCollection']();
}

export function StartFullCollection() {
  return window['go']['main']['App']['StartFullCollection']();
}

export function UpdatePricing() {
  return window['go']['main']['App']['UpdatePricing']();
}

export function UpdateQuotaConfig(arg1) {
  return window['go']['main']['App']['UpdateQuotaConfig'](arg1);
}
