// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectStatus() {
  return window['go']['main']['App']['CollectStatus']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetTimeSeriesData() {
  return window['go']['main']['App']['GetTimeSeriesData']();
}

export function StartCollection() {
  return window['go']['main']['App']['StartCollection']();
}
